# Generated by Django 5.0.2 on 2024-02-26 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('reviewed', 'Reviewed'), ('started', 'Started'), ('closed', 'Closed')], default='new', max_length=25)),
                ('summary', models.TextField()),
                ('opened_on', models.DateTimeField(auto_now_add=True, verbose_name='date opened')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
